#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

# Run test scripts here, maybe
# python "$OPENSHIFT_REPO_DIR"wsgi/myproject/manage.py test --top-level-directory "$BASE_DIR"
python "$OPENSHIFT_REPO_DIR"wsgi/myproject/manage.py test lists
